S3_CONFIG_KEY = "bucket"
AWS_ACCESS_KEY = "access_key"
AWS_SECRET_KEY = "secret_key"
AWS_REGION_NAME = "region_name"
AWS_BUCKET_NAME = "bucket_name"
AWS_RESPONSE_CONTENT = "Contents"
AWS_RESPONSE_PREFIXES = "CommonPrefixes"

FTP_SERVER_KEY = "ftp_server"
FTP_USER_NAME = "username"
FTP_PASSWORD = "password"
FTP_KEY_FILE = "keyfile"
FTP_HOST = "host"
FTP_PORT = "port"

REMOTE_DIRECTORY = "remotedirectory"
LOCAL_PATH = "localpath"
